#!/usr/bin/env bash
# Build db/init/01-demo-seed.sql from a small sample of a live NeuralWire database.
#
#   SOURCE_DATABASE_URL=postgresql://... db/pull_demo_seed.sh
#
# The source is only read: every session runs with default_transaction_read_only.
# Sampled rows are loaded into a throwaway local Postgres, third-party text is
# blanked (provider summaries, and prompts that embed scraped article text), and
# the result is dumped as the seed. Requires Docker; no local Postgres tools needed.
set -euo pipefail

: "${SOURCE_DATABASE_URL:?set SOURCE_DATABASE_URL to the database to sample}"

TICKERS="'NVDA','AMD','TSLA'"
ARTICLES_PER_TICKER=40
PG_IMAGE=postgres:18 # must match the source server's major version (and docker-compose.yml)
BUILD=nw-demo-build
OUT=db/init/01-demo-seed.sql

cd "$(dirname "$0")/.."

source_psql() {
    docker run --rm -i -e SOURCE_DATABASE_URL -e PGOPTIONS="-c default_transaction_read_only=on" \
        "$PG_IMAGE" sh -c 'psql "$SOURCE_DATABASE_URL" -v ON_ERROR_STOP=1 -q "$@"' -- "$@"
}

build_psql() {
    docker exec -i "$BUILD" psql -U demo -d demo -v ON_ERROR_STOP=1 -q "$@"
}

# Copy the rows of $1 selected by the WHERE clause $2 from the source into the build DB.
copy_rows() {
    local table=$1 where=$2
    source_psql -c "\\copy (SELECT * FROM $table WHERE $where) TO STDOUT" |
        build_psql -c "\\copy $table FROM STDIN"
    echo "  $table: $(build_psql -At -c "SELECT count(*) FROM $table")"
}

echo "Starting throwaway build database..."
docker rm -f "$BUILD" >/dev/null 2>&1 || true
docker run -d --name "$BUILD" -e POSTGRES_USER=demo -e POSTGRES_PASSWORD=demo -e POSTGRES_DB=demo \
    "$PG_IMAGE" >/dev/null
trap 'docker rm -f "$BUILD" >/dev/null 2>&1 || true' EXIT
until docker exec "$BUILD" pg_isready -U demo -d demo -q 2>/dev/null; do sleep 1; done
sleep 2 # the entrypoint restarts the server once after initialisation

echo "Copying schema..."
docker run --rm -e SOURCE_DATABASE_URL "$PG_IMAGE" \
    sh -c 'pg_dump "$SOURCE_DATABASE_URL" --schema-only --no-owner --no-privileges' |
    build_psql >/dev/null

echo "Sampling rows..."
RUNS="SELECT id FROM (
        SELECT ar.id, row_number() OVER (PARTITION BY ar.ticker ORDER BY a.published_at DESC) AS n
        FROM analysis_runs ar JOIN articles a ON a.id = ar.article_id
        WHERE ar.ticker IN ($TICKERS)
      ) ranked WHERE n <= $ARTICLES_PER_TICKER"

# Parents before children, for foreign keys.
copy_rows articles "id IN (SELECT article_id FROM analysis_runs WHERE id IN ($RUNS))"
copy_rows analysis_runs "id IN ($RUNS)"
copy_rows ticker_artefacts "id IN (
    SELECT DISTINCT ON (ticker, artefact_type) id FROM ticker_artefacts
    WHERE ticker IN ($TICKERS) ORDER BY ticker, artefact_type, generated_at DESC)"
copy_rows ticker_events "ticker IN ($TICKERS)"
copy_rows ticker_classification "ticker IN ($TICKERS)"
copy_rows ticker_colors "ticker IN ($TICKERS)"
copy_rows summaries "ticker IN ($TICKERS)"
copy_rows earnings "ticker IN ($TICKERS)"
copy_rows earnings_reactions "earnings_id IN (SELECT id FROM earnings WHERE ticker IN ($TICKERS))"
copy_rows historical_prices "ticker IN ($TICKERS) AND date >= CURRENT_DATE - 365"

echo "Blanking third-party text and resetting id sequences..."
build_psql <<'SQL'
UPDATE articles SET api_summary = NULL, scrape_error = NULL;
UPDATE analysis_runs SET prompt = NULL;
UPDATE ticker_artefacts SET prompt = NULL;

-- Point every serial sequence past the copied ids, so new inserts don't collide.
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.table_name, c.column_name, pg_get_serial_sequence(c.table_name, c.column_name) AS seq
        FROM information_schema.columns c
        WHERE c.table_schema = 'public' AND c.column_default LIKE 'nextval(%'
    LOOP
        EXECUTE format('SELECT setval(%L, COALESCE((SELECT max(%I) FROM %I), 0) + 1, false)',
                       r.seq, r.column_name, r.table_name);
    END LOOP;
END $$;
SQL

echo "Writing $OUT..."
mkdir -p "$(dirname "$OUT")"
{
    echo "-- NeuralWire demo seed: a sample of $TICKERS generated by db/pull_demo_seed.sh."
    echo "-- Loaded automatically by Postgres the first time the compose database starts."
    docker exec "$BUILD" pg_dump -U demo -d demo --no-owner --no-privileges
} >"$OUT"

echo "Done: $OUT ($(du -h "$OUT" | cut -f1))"
